### PR TITLE
add methods for querying the verison and path of libfuse

### PR DESCRIPTION
**Pull request by N-Coder**
Might be interesting for debugging to get more information about the current environment.
I didn't test every OS, but the given function names should cover pretty much everything.

Note: maybe this generic functionality (together with `fuse_exit`) should be in a file that can be shared between low- and high-level API

### CODE REVIEW

**Comment by s-m-e** [comment]
> Might be interesting for debugging [...]

Certainly, yes. Thanks for this.

> Note: maybe this generic functionality [...]

Yes, indeed. I'll merge this as it is but I will eventually isolate it into a common low & high level library.

**Comment by s-m-e** [comment]
FYI, I have not updated the readme and contributing files in master yet, but I intend to keep development within the "develop" branch. I redirected your pull request accordingly. Hope you don't mind.

**Comment by N-Coder** [comment]
All good, thanks. Do you have a rough schedule in mind when you'll be releasing the first somewhat stable version? I'm currently shipping the latest fusepy development version together with my own project because there hasn't been a release in ages...

**Comment by s-m-e** [comment]
@N-Coder Depends on your definition of "stable". I am still figuring out how to make the various BSDs for instance work in a CI-kind-of way. Plus non-x86-64 architectures where applicable. Qemu is the solution, no question, but it is non-trivial. I want to go from there with any further, significant changes. I have some time allocated for this within the next two weeks.

With respect to your project: I uploaded 0.0.2 of this project to PyPI already. My filesystem, LoggedFS-python, is using it. Its current release is explicitly requiring refuse 0.0.2. You can start doing the same, if you want. You know the fusepy source code well, it should not be too much of a risk for you. Breaking changes, if there are any, will be denoted by going to 0.1.0, 0.2.0 etc ... and I'll note them (all) in [here](https://github.com/pleiszenburg/refuse/blob/develop/CHANGES.md) and [here](https://github.com/pleiszenburg/refuse/blob/develop/docs/porting.md).

**Pull request merged**
